---
image: dokku/ci-docker-image

stages:
  - build
  - deploy

variables:
  GIT_DEPTH: 0

build-base:
  stage: build
  only:
    - master
  variables:
    GIT_REMOTE_URL: ssh://dokku@${DOKKU_HOST}:22/ebsi-diplomata
  script: 
    - dokku-deploy

deploy:
  stage: deploy
  only:
    - master
  variables:
    GIT_REMOTE_URL: ssh://dokku@${DOKKU_HOST}:22/ebsi-diplomata
  script: 
    - dokku-deploy
  after_script: 
    - dokku-unlock