FROM ebsi-base-dev:local

ENV TMPDIR ${HOMEDIR}/tmp
ENV STORAGE ${HOMEDIR}/storage

RUN apt-get update && apt-get install -y \
    sqlite3

WORKDIR ${HOMEDIR}/app

COPY ./wallet/requirements.txt .
COPY ./wallet/requirements-dev.txt .

RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

COPY ./wallet .

RUN mkdir -p ${TMPDIR}

ENTRYPOINT ["./entrypoint.dev.sh"]
