FROM python:3.10-slim-bullseye

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE  1

ENV USERNAME dev
ENV HOMEDIR /home/${USERNAME}
ENV WALTDIR ${HOMEDIR}/waltid-ssikit

RUN chmod 1777 /tmp
RUN apt-get update && apt-get install -y \
    gcc \
    openjdk-17-jre \
    openjdk-17-jdk

COPY ./waltid-ssikit ${WALTDIR}
WORKDIR ${WALTDIR}
RUN ./ssikit.sh build
RUN rm -rf data && mkdir -p data/ebsi

WORKDIR ${HOMEDIR}

COPY ./ssi-lib/commands /usr/local/sbin

COPY ./ssi-lib ./ssi-lib
WORKDIR ssi-lib 
RUN rm -rf build/ dist/ ssi_lib.egg-info
RUN python3 setup.py install 
WORKDIR ${HOMEDIR}
RUN rm -rf ./ssi-lib
