version: '3.8'

services:
  issuer:
    container_name: issuer
    build:
      context: .
      dockerfile: Dockerfile.issuer
    ports:
      - 7000:7000
    expose:
      - 7000
    environment:
      - DEBUG=1
      - DATABASE=postgres
      - SQL_DATABASE=issuer_db
      - SQL_USER=issuer_db_user
      - SQL_PASSWORD=issuer_db_password
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_HOST=issuer-db
      - SQL_PORT=5432
    volumes:
      - ./issuer:/home/issuer/app
      - ./storage/issuer:/home/issuer/storage
      - ./commands:/usr/local/sbin
      - type: bind
        source: ./resources/bearer-token.txt
        target: /home/issuer/waltid-ssikit/data/ebsi/bearer-token.txt
    depends_on:
      - postgres
  verifier:
    container_name: verifier
    build:
      context: .
      dockerfile: Dockerfile.verifier
    ports:
      - 7001:7001
    expose:
      - 7001
    environment:
      - DEBUG=1
    volumes:
      - ./verifier:/home/verifier/app
      - ./storage/verifier:/home/verifier/storage
      - ./commands:/usr/local/sbin
  postgres:
    container_name: issuer-db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=issuer_db
      - POSTGRES_USER=issuer_db_user
      - POSTGRES_PASSWORD=issuer_db_password
volumes:
  postgres_data:
