CREATE TABLE IF NOT EXISTS key (
  id SERIAL PRIMARY KEY,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS did (
  id SERIAL PRIMARY KEY,
  key INT,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL,
  CONSTRAINT fk_key FOREIGN KEY(key)
    REFERENCES key(id)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vc (
  id SERIAL PRIMARY KEY,
  did INT,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL,
  CONSTRAINT fk_holder FOREIGN KEY(did)
    REFERENCES did(id)
      ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS vp (
  id SERIAL PRIMARY KEY,
  did INT,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL,
  CONSTRAINT fk_holder FOREIGN KEY(did)
    REFERENCES did(id)
      ON DELETE NO ACTION
);
