CREATE TABLE IF NOT EXISTS key (
  id SERIAL PRIMARY KEY,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS did (
  id SERIAL PRIMARY KEY,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL,
  key VARCHAR(255) NOT NULL,
  CONSTRAINT fk_key FOREIGN KEY(key)
    REFERENCES key(alias)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vc (
  id SERIAL PRIMARY KEY,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL,
  holder VARCHAR(255) NOT NULL,
  CONSTRAINT fk_holder FOREIGN KEY(holder)
    REFERENCES did(alias)
      ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS vp (
  id SERIAL PRIMARY KEY,
  alias VARCHAR(255) NOT NULL UNIQUE,
  body JSONB NOT NULL,
  holder VARCHAR(255) NOT NULL,
  CONSTRAINT fk_holder FOREIGN KEY(holder)
    REFERENCES did(alias)
      ON DELETE NO ACTION
);
