#!/bin/bash

usage_string="usage: ./$(basename "$0") [OPTIONS]

DID creation

Options:
  -k, --key                       Specific key (ID or alias). If not provided,
                                  the last created key will be used; if no such
                                  key exissts, then a newly created key will be
                                  usef, which will be generated accordng to an
                                  algorithm secpified as follows.
  -a, --algo [Ed25519|Secp256k1]  Keygen algorithm. Default: Ed255519

Examples
  $ $(basename "$0")
  $ $(basename "$0") --key d7080431b17f4adea29e50181115d810
  $ $(basename "$0") --algo Secp256k1
"

usage() { echo -n "$usage_string" 1>&2; }

KEY=
ALGO=Ed25519

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        -a|--algo)
            if [ "$2" == "Ed25519" ] || [ "$2" == "Secp256k1" ]; then
                ALGO="$2"
            else
                echo "[-] Unrecongized keygen algorithm: ${2}"
                usage
                exit 1
            fi
            shift
            shift
            ;;
        -k|--key)
            KEY="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

cd ${WALTDIR}

if [ -z ${KEY} ]; then
    KEY=$(get-key)
    if [ $? == 2 ]; then
        KEY=$(create-key --algo ${ALGO})
    fi
fi

OUTDIR="${STORAGE}/tmp"
mkdir -p $OUTDIR
OUTFILE="${OUTDIR}/created.json"

./ssikit.sh did create \
    --did-method ebsi \
    --key ${KEY} \
    --out ${OUTFILE} \
    > /dev/null 2>&1

echo ${OUTFILE}
exit 0
