#!/bin/bash

usage_string="usage: ./$(basename "$0") [OPTIONS]

Get the last created key. Exit with 2 if no created key exists. See below for
more options.

Options:
  --list    List all created keys.
  --nr      Get the key which appears at position nr of the list, counting from
            one. Exit with 2 if the provided number exceeds limits.
  --number  Number of created keys.

Examples
  $ $(basename "$0")
  $ $(basename "$0") --nr 7
  $ $(basename "$0") --list 
  $ $(basename "$0") --number 
"

usage() { echo -n "$usage_string" 1>&2; }

get_nr_keys() {
    NR_KEYS=$(./ssikit.sh key list | grep -c "\- [0-9]*:")
    echo $NR_KEYS
}

get_key() { 
    POS=$1
    if [[ "$POS" -lt 1 ]] ; then
        echo "Index cannot be less than one: ${POS} < 1"
        exit 2
    fi
    NR_KEYS=$(get_nr_keys)
    if [[ "$POS" -gt "$NR_KEYS" ]]; then
        echo "Provided number exceeds limits: ${POS} > ${NR_KEYS}"
        exit 2
    fi
    KEY=$(./ssikit.sh key list \
        | grep "\- ${POS}:" \
        | awk -F' ' '{print $3}' \
        | tr -d '"')
    echo $KEY
}

get_last_key() {
    NR_KEYS=$(get_nr_keys)
    if [ ${NR_KEYS} == 0 ]; then
        echo "No created keys found" && exit 2
    fi
    POS=${NR_KEYS}
    echo $(get_key $POS)
}

get_key_list() {
    ./ssikit.sh key list
}


ACTION=DO_SHOW

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --list)
            ACTION=DO_LIST
            shift
            ;;
        --number)
            ACTION=DO_COUNT
            shift
            ;;
        --nr)
            POS="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

cd $WALTDIR

case $ACTION in
    DO_SHOW)
        if [ -z $POS ]; then
            get_last_key
        else
            get_key $POS
        fi
        shift
        ;;
    DO_LIST)
        get_key_list
        shift
        ;;
    DO_COUNT)
        get_nr_keys
        shift
        ;;
esac

exit 0
