#!/bin/bash

usage_string="usage: ./$(basename "$0") [OPTIONS]

Issue VC and return the path to the corresponding file.

Arguments:
  --issuer-did DID  Current issuer DID
  --holder-did DID  DID of VC holder
  --export OUTFILE  File to export key after generation

Options:
  --template        VC template to use. Default: VerifiableDiploma
  --proof-type      Proof type to be used for issuance. Default: LD_PROOF

Examples
  $ $(basename "$0") --holder-did did:ebsi:zph2s2XSe6F9rn55j1QYH1C
"

usage() { echo -n "$usage_string" 1>&2; }

set -e

TEMPLATE=VerifiableDiploma
PROOF_TYPE=LD_PROOF

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --issuer-did)
            ISSUER_DID="$2"
            shift
            shift
            ;;
        --holder-did)
            HOLDER_DID="$2"
            shift
            shift
            ;;
        --export)
            OUTFILE="$2"
            shift
            shift
            ;;
        --template)
            TEMPLATE="$2"
            shift
            shift
            ;;
        --proof-type)
            HOLDER_DID="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${HOLDER_DID} ]; then
    echo "[-] No holder DID provided"
    usage && exit 1
fi

if [ -z ${ISSUER_DID} ]; then
    echo "[-] No issuer DID provided"
    usage && exit 1
fi

if [ -z ${OUTFILE} ]; then
    echo "[-] No export file provided"
    usage && exit 1
fi

cd $WALTDIR

./ssikit.sh vc issue \
    --template ${TEMPLATE} \
    --issuer-did ${ISSUER_DID} \
    --subject-did ${HOLDER_DID} \
    --proof-type ${PROOF_TYPE} \
    --proof-purpose assertion \
    --interactive \
    ${OUTFILE} > /dev/null
# TODO: Check here output of the above command and exit with appopriate status
# code
exit 0

