#!/bin/bash

usage_string="usage: ./$(basename "$0") [OPTIONS]

Create a verifiable presentation

Arguments:
  --holder-did DID        DID of the holder owning the provided credentials.
                          Must coincide with the credentialSubject.id attribute of
                          of the provided credentials.
  -c, --credential FILE   File containing verifiable credential

Examples
  $ $(basename "$0") -c vc1.json -c vc2.json \
                     --holder-did did:ebsi:zph2s2XSe6F9rn55j1QYH1C
"

usage() { echo -n "$usage_string" 1>&2; }

set -e

HOLDER_DID=
CREDENTIALS=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --holder-did)
            HOLDER_DID="$2"
            shift
            shift
            ;;
        -c|--credential)
            CREDENTIALS+=" $2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${HOLDER_DID} ]; then
    echo "[-] No holder DID provided"
    usage && exit 1
fi

if [ ${#CREDENTIALS[@]} -eq 0 ]; then
    echo "[-] No credentials provided"
    usage && exit 1
fi
    
cd $WALTDIR

resp=$(
    ./ssikit.sh vc present \
        --holder-did ${HOLDER_DID} \
        ${CREDENTIALS}
)

echo $resp

exit 0
