#!/bin/bash

usage_string="usage: ./$(basename "$0") [OPTIONS]

Verify credential and return results

Arguments:
  -c, --credential FILE     Credential to verify

Options:
  TODO: Specify options

Examples
  $ $(basename "$0") ...
"

usage() { echo -n "$usage_string" 1>&2; }

set -e

CREDENTIAL=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        -c|--credential)
            CREDENTIAL="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${CREDENTIAL} ]; then
    echo '[-] No credential file provided'
    usage && exit 1
fi

cd $WALTDIR

resp=$(
  ./ssikit.sh vc verify \
      --policy JsonSchemaPolicy \
      --policy TrustedSubjectDidPolicy \
      --policy TrustedIssuerDidPolicy \
      --policy SignaturePolicy \
      ${CREDENTIAL}
)

echo $resp
exit 0

