# Generated by Django 4.0.3 on 2022-04-20 15:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Did',
            fields=[
                ('alias', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('body', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('auth_provider', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(choices=[('alumnus', 'Alumnus'), ('student', 'Student'), ('helpdesk', 'Helpdesk'), ('admin', 'Admin')], default='alumnus', max_length=32)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ssi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=256)),
                ('body', models.JSONField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ssi.did')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('alias', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('body', models.JSONField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ssi.did')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('extern_id', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=2048)),
                ('last_name', models.CharField(max_length=2048)),
                ('father_name', models.CharField(max_length=2048, null=True)),
                ('mother_name', models.CharField(max_length=2048, null=True)),
                ('birthyear', models.CharField(max_length=4, null=True)),
                ('birthdate', models.CharField(max_length=64, null=True)),
                ('afm', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='ssi.user')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssi.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
